config/routes.rb
Manabase::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  root :to => 'pages#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  authenticates_with_sorcery!

  field :name
  field :email
  field :password
  field :password_confirmation

  attr_accessible :name, :email, :password, :password_confirmation

  validates_confirmation_of :password, :message => "should match confirmation"
  validates_presence_of :password
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now[:error] = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manabase</title>
  <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'> 
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="topbar">
    <div class="container">
      <h3><a href="/">manabase</a></h3>
      <ul>
        <li><a href="/#topdecks">Top Decks</a></li>
        <li><a href="/#cards">Cards</a></li>
      </ul>
      <form>
        <input type="text" placeholder="Search"/>
      </form>
      <ul class="secondary-nav">
      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle"><%= current_user.name %></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My decks", "/#mydecks" %></li>
            <li><%= link_to "Profile", "/#profile" %></li>
            <li><%= link_to "Settings", "/#settings" %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
      </ul>
    </div>
  </div>

  <div class="container">
    <%= yield %>
    <footer>
      <p></p>
    </footer>
  </div>
</body>
</html>

app/views/pages/index.html.erb
<div class="hero-unit">
  <h1>Welcome to Manabase</h1>
  <p>Your gateway to competitive Magic: the Gathering.</p>
  <h4>New to Manabase?</h4>

  <p><a href="/signup" class="btn primary large">Sign up! &raquo; <small>It's free</small></a></p>
</div>

<div class="row">
  <div class="span4">
    <h3>Top decklists</h3>
      <p>Find out what decks currently perform well in tournaments and analyse the latest metagame trends.</p>
  </div>
  <div class="span4">
    <h3>Manage your decks</h3>
    <p>
      Build your decks with our user-friendly deck editor. Keep your decklists in a one place and access them from any computers.
    </p>
 </div>
  <div class="span4">
    <h3>Test your decks</h3>
    <p>Play against other player right from your browser.</p>
  </div>
  <div class="span4">
    <h3>Check card prices</h3>
    <p>Find the best prices for the cards you need.</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-header">
  <h2>Sign up</h2>
</div>

<div class="row">
  <div class="span10">
  <% if @user.errors.any? %>
    <div class="alert-message block-message error">
      <a class="close" href="#">×</a>
      <p><strong>Invalid form.</strong></p>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @user, :html => { :class => "form-stacked" } do |f| %>

    <div class="clearfix">
      <%= f.label :name %>
      <div class="input"><%= f.text_field :name %></div>
    </div>

    <div class="clearfix">
      <%= f.label :email %>
      <div class="input"><%= f.email_field :email %></div>
    </div>

    <div class="clearfix">
      <%= f.label :password %>
      <div class="input"><%= f.password_field :password %></div>
    </div>

    <div class="clearfix">
      <%= f.label :password_confirmation %>
      <div class="input"><%= f.password_field :password_confirmation %></div>
    </div>

    <div class="actions">
      <%= f.submit "Sign up", :class => "btn primary" %>
    </div>
  <% end %>
  Already have an account? <%= link_to "Log in", login_path() %>
  </div>
</div>